### PR TITLE
Better hud

### LINKED ISSUE #24: Improve HUD
Change the slidder by number input, because user does not know what laps and players are set in the game.

### PR DESCRIPTION
**Pull request by AdrienJarretier**
closes #24

### CODE REVIEW

**Comment by guillaume-gomez** [comment]
screen shot 2016-05-21 at 09 42 12

TADDAAAAA

**Comment by AdrienJarretier** [comment]
nice :v: very nice, i caught 2 little bugs though
1. if you snap the window (hence it's taking half the sreen) the input chat message overlaps over the end of the test "message :" effectively hiding it a little
2. on chrome the cars thumbnails don't appear in the car selection menu

**Comment by guillaume-gomez** [comment]
1) I will fix that issue
2) I dont really want to manage cars thumbnails on chrome. This is a minor issue and I think we should focus on major things (but I you think it's important go ahead)

**Comment by AdrienJarretier** [comment]
Agreed about thumbnails on chrome

I'll wait for the fix of the chat if you think it's important, but i't not a very big deal either in my opinion, the interface is nice enough like that

**Comment by guillaume-gomez** [comment]
it's done for the chat issue

**Comment by AdrienJarretier** [comment]
I have no idea how to fix it with :boot:strap , no point in wasting much time on this tiny issue, I'm merging this, we'll have a great and nice looking webpage

**Pull request merged**
