### PR TITLE
fix tile rotation in the editor

### PR DESCRIPTION
**Pull request by guillaume-gomez**
https://github.com/guillaume-gomez/NodeRace/issues/35

### CODE REVIEW

**Comment by AdrienJarretier** [comment]
works fine when putting tiles BUT
still an issue on deletion, if you want to delete a rotated tile you have to right click nearby

**Comment by guillaume-gomez** [comment]
OK i will investigate why?

**Comment by guillaume-gomez** [comment]
tiles can be deleted

**Comment by AdrienJarretier** [comment]
Tested, it works .. unless you load a track x)

**Comment by AdrienJarretier** [comment]
if you load an existing track you still have the issue when trying to delete a tile sorry :tongue:

**Comment by guillaume-gomez** [comment]
The problem is about the levels loaded themselves. This is the result of wrong computations.

**Comment by AdrienJarretier** [comment]
:neutral_face: oh ... ok, I'll take care of this

**Comment by AdrienJarretier** [comment]
I'll make another PR to fix this issue, I'm merging this

**Pull request merged**
